In [1]:
import numpy as np

In [2]:
#1D array
a = np.array([1, 2, 3, 4])
print("1D array:", a)

1D array: [1 2 3 4]


In [6]:
#2D array
b = np.array([[1, 2], [3, 4]])
print("2D array", b)

2D array [[1 2]
 [3 4]]


In [11]:
# zeros and ones
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
print("Zeros:\n",zeros)
print("Ones: \n", ones)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# a 3 by 3 matrix the value in bracket can be changed to any number : n by n matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Array Operations

x = np.array([10, 30, 45])
y = np.array([1, 3, 4])

print(x+y)
print(x*y)
print(np.sqrt(x))
print(x/2)

[11 33 49]
[ 10  90 180]
[3.16227766 5.47722558 6.70820393]
[ 5.  15.  22.5]


In [20]:
arr = np.arange(10) #numbers 0-9
print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice 2 to 5:", arr[2:6])
even_nums = arr[arr % 2 != 0]
print(even_nums)

Array: [0 1 2 3 4 5 6 7 8 9]
First element: 0
Last element: 9
Slice 2 to 5: [2 3 4 5]
[1 3 5 7 9]


In [1]:
#Pandas basics. Series
import pandas as pd

data = pd.Series([10, 20, 30],
index=["a", "b", "c"])
print(data)
print("Access eleent b:", data["b"])

a    10
b    20
c    30
dtype: int64
Access eleent b: 20


In [2]:
#Dataframe
df = pd.DataFrame({
    "Tree": ["Mango", "Accaia", "Pine"],
    "Age": [2, 4, 5],
    "CO2_absorbed": [50, 45, 23]
})

print(df)

     Tree  Age  CO2_absorbed
0   Mango    2            50
1  Accaia    4            45
2    Pine    5            23


In [4]:
#Selecting and filtering
print("Select column Age:\n", df["Age"])
print("\n Trees older than 3 years: \n", df[df["Age"] > 3])
print("\n Select first row: \n", df.iloc[0])

Select column Age:
 0    2
1    4
2    5
Name: Age, dtype: int64

 Trees older than 3 years: 
      Tree  Age  CO2_absorbed
1  Accaia    4            45
2    Pine    5            23

 Select first row: 
 Tree            Mango
Age                 2
CO2_absorbed       50
Name: 0, dtype: object


In [5]:
#Performing simple stats
print("Average age:", df["Age"].mean())
print("Max CO2 absorbed:", df["CO2_absorbed"].max())
print("\n Summary: \n", df.describe())

Average age: 3.6666666666666665
Max CO2 absorbed: 50

 Summary: 
             Age  CO2_absorbed
count  3.000000      3.000000
mean   3.666667     39.333333
std    1.527525     14.364308
min    2.000000     23.000000
25%    3.000000     34.000000
50%    4.000000     45.000000
75%    4.500000     47.500000
max    5.000000     50.000000


In [5]:
#Test on Dataframes
import pandas as pd
df = pd.DataFrame({
    "TreeType": ["Mango", "Pine", "Cactus"],
    "Height_m": [2, 56, 6],
    "Stage": ["Seedling", "Grown", "Seedling"]
})
seed_count = (df["Stage"] == "Seedling").sum()
avg_height = df["Height_m"].mean()
tallest_tree = df.loc[df["Height_m"].idxmax()]

print("Seedling count:\n", seed_count)
print("\nTallest:\n", tallest_tree)
print("\nAverage height:\n", avg_height)

Seedling count:
 2

Tallest:
 TreeType     Pine
Height_m       56
Stage       Grown
Name: 1, dtype: object

Average height:
 21.333333333333332
